version: '3.7'

services:
  meilisearch:
    container_name: safari-test
    ports:
      - '7700:7700'
    environment:
      - .env
    volumes:
    restart: unless-stopped

volumes:
  data:
    driver: local

networks:
  app-tier:
    driver: bridge
